### ISSUE TITLE
Nav bar icons crowded with dynamic long strings

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/vector-addition#286] opened 2024-11-07 19:52 UTC
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1165
When string get a longer dynamically (not with stringTest=long) the icons in the nav bar can get a bit crowded. The text buts up against the text of the next icon and the highlights overlap. Compare to long string from stringTest=long. This is fairly minor, and may show up elsewhere but missed.

**Visuals**
Dynamic long strings
![navclose](https://github.com/user-attachments/assets/7e145613-a490-4f37-8e8b-b10ad7ef7207)
Non-dynamic long strings
![longspread](https://github.com/user-attachments/assets/75fac669-2cff-4fa3-8fc0-123994280204)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Vector Addition‬
URL: https://phet-dev.colorado.edu/html/vector-addition/1.1.0-rc.1/phet/vector-addition_all_phet.html
Version: 1.1.0-rc.1 2024-11-06 21:59:28 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment] 2024-11-07 19:58
Edit to add, they can also be misaligned if they change by different lengths.
![outofline](https://github.com/user-attachments/assets/8d1bcf86-b557-4bb9-85eb-e0e828de450b)

**Comment by pixelzoom** [comment] 2024-11-07 20:00
Reproduced in main, for example:

<img width="431" alt="screenshot_3584" src="https://github.com/user-attachments/assets/6734915a-5b52-49de-a445-b3760bba909e">

This was not a problem in test for other recent sims, for example RPAL 1.3.0-dev.6:

<img width="361" alt="screenshot_3583" src="https://github.com/user-attachments/assets/de8080c8-f70f-497e-8422-4cd9c454215d">

So I suspect that a regression has been introduced in joist.

**Comment by pixelzoom** [comment] 2024-11-07 20:04
These problems are also present in [1.1.0-dev.5]([vector-addition_all_phet.html](https://phet-dev.colorado.edu/html/vector-addition/1.1.0-dev.5/phet/vector-addition_all_phet.html)) which was used for dev tests https://github.com/phetsims/qa/issues/1163 and https://github.com/phetsims/qa/issues/1164.

**Comment by pixelzoom** [comment] 2024-11-07 23:43
It looks like this problem is specific to the screen names in Vector Addition.  I do not see the same problem in main for RPAL, for example. 

And the problem has been around for awhile -- I it in Vector Addition 1.1.0-dev.3 from 7/11/2023.

Maybe a font metrics problem? Maybe because the overlapping screen names contain numbers? (Explore 1D, Explore 2D)

**Comment by pixelzoom** [comment] 2024-11-07 23:49
> Maybe a font metrics problem? Maybe because the overlapping screen names contain numbers? (Explore 1D, Explore 2D)

I tried replacing the numbers with characters, and no change. I think there's just something buggy with the navbar layout that is being exposed by these particular screens names.

And it only seems to be a problem with the first 2 screen names, because the problem looks like this with `?screens=1,2&stringTest=dynamic`:

<img width="306" alt="screenshot_3588" src="https://github.com/user-attachments/assets/845ca0a9-3b14-43fa-8695-00c8879327d8">

**Comment by Nancy-Salpepi** [comment] 2024-11-08 00:35
I opened up a similar issue a while back relating to color vision: https://github.com/phetsims/joist/issues/982

**Comment by pixelzoom** [comment] 2024-11-08 03:09
Thanks @Nancy-Salpepi.  I've reopened https://github.com/phetsims/joist/issues/982 - unfortunate that it was closed without addressing.

**Comment by pixelzoom** [comment] 2024-11-08 23:40
Discussed with @arouinfar.  This is not blocking for the 1.1 release, and we'll close this as "won't fix".

Thanks for reporting @KatieWoe.  It resulted in https://github.com/phetsims/joist/issues/982 getting reopened, so hopefully it will be prioritized and addressed.

Closing.

**Closed by pixelzoom** 2024-11-08 23:40 UTC
Labels: type:bug
