### ISSUE TITLE
Label on first screen may or may not switch sides

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/vector-addition#259] opened 2019-10-28 21:54 UTC
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/445
When on the x-axis scene of the first screen, the label for a vector will change sides depending on if the vector is positive or negative.  This does not occur on the y-axis scene however.

**Visuals**
![switchnotswitch](https://user-images.githubusercontent.com/41024075/67721016-1f300a80-f99b-11e9-8e4b-19e83f0670b4.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Vector Addition‬
URL: https://phet-dev.colorado.edu/html/vector-addition/1.0.0-rc.1/phet/xhtml/vector-addition_all.xhtml
Version: 1.0.0-rc.1 2019-10-23 17:30:32 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment] 2019-10-28 21:59
There is no special strategy for the horizontal vs vertical orientations in the _Explore 1D_ screen, and no intention to make +-x and +-y have similar behavior.  All screens you the same strategy for positioning the label, illustrated at https://github.com/phetsims/vector-addition/issues/93#issuecomment-535085310.  So this is working as intended.

**Comment by pixelzoom** [comment] 2019-10-28 22:00
There is no special strategy for the horizontal vs vertical orientations in the _Explore 1D_ screen, and no intention to make +-x and +-y have similar behavior.  All screens use the same strategy for positioning the label, illustrated at https://github.com/phetsims/vector-addition/issues/93#issuecomment-535085310.  So this is working as intended. 

@arouinfar if you'd like to change this, please review https://github.com/phetsims/vector-addition/issues/93 and specify the new behavior.

**Comment by arouinfar** [comment] 2019-10-28 22:10
Thanks @KatieWoe @pixelzoom. I think the current behavior is fine as-is, closing.

**Closed by arouinfar** 2019-10-28 22:10 UTC
Labels: design:general

**Comment by pixelzoom** [comment] 2019-10-28 22:19
Thanks for reporting @KatieWoe!
