### ISSUE TITLE
CT cannot drag tip when not on graph

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/vector-addition#272] opened 2021-02-04 16:28 UTC
```
vector-addition : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/vector-addition/vector-addition_en.html?continuousTest=%7B%22test%22%3A%5B%22vector-addition%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1612446304630%22%2C%22timestamp%22%3A1612450352450%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000
Uncaught Error: Assertion failed: Cannot drag tip when not on graph
Error: Assertion failed: Cannot drag tip when not on graph
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/assert/js/assert.js:25:13)
at VectorNode.updateTipPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/vector-addition/js/common/view/VectorNode.js:362:15)
at tipListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/vector-addition/js/common/view/VectorNode.js:228:14)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/axon/js/TinyEmitter.js:71:18)
at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/axon/js/Property.js:289:25)
at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/axon/js/Property.js:187:14)
at Vector2Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/axon/js/Property.js:359:32)
at DragListener.reposition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/scenery/js/listeners/DragListener.js:630:36)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/scenery/js/listeners/DragListener.js:294:12
at DragListener.onPress (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/scenery/js/listeners/PressListener.js:619:17)
id: Bayes Chrome
Snapshot from 2/4/2021, 6:45:04 AM
```

**Comment by pixelzoom** [comment] 2021-02-04 19:44
Duplicate of #271. Closing.

**Closed by pixelzoom** 2021-02-04 19:44 UTC
Labels: type:automated-testing
