### ISSUE TITLE
labels overlap for vector <-x,0>

### ISSUE THREAD

**Issue by megan-phet** [phetsims/vector-addition#264] opened 2019-10-31 18:04 UTC
<b>Test Device</b>
- MacBook Pro

<b>Operating System</b>
- 10.15
- 10.12.6

<b>Browser</b>
- All latest

<b>Problem Description</b>
For phetsims/QA#445

The values will overlap with negative horizontal vectors.

<b>Steps to Reproduce</b>
1. Check the Values box

2. Click the angle vectors button. 
<img width="73" alt="Screen Shot 2019-10-31 at 11 49 48 AM" src="https://user-images.githubusercontent.com/40698031/67972584-969cae80-fbd4-11e9-94b2-4fe12e9559ea.png">

3. Pick eather of these conponents.
<img width="73" alt="Screen Shot 2019-10-31 at 11 49 15 AM" src="https://user-images.githubusercontent.com/40698031/67972790-fabf7280-fbd4-11e9-9422-19cdc044d4c5.png">         <img width="74" alt="Screen Shot 2019-10-31 at 11 49 22 AM" src="https://user-images.githubusercontent.com/40698031/67972876-1f1b4f00-fbd5-11e9-878b-e34f35696ce6.png">

4. Make the horizontal vector negative.

<b>Visuals</b>
![Kapture 2019-10-31 at 11 42 07](https://user-images.githubusercontent.com/40698031/67972426-47567e00-fbd4-11e9-90aa-d352244943aa.gif)

<details>
<summary><b>Troubleshooting Information</b></summary>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Vector Addition: Equations‬
URL: https://phet-dev.colorado.edu/html/vector-addition-equations/1.0.0-rc.1/phet/vector-addition-equations_all_phet.html
Version: 1.0.0-rc.1 2019-10-23 17:35:42 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.2 Safari/605.1.15
Language: en-US
Window: 1408x734
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by megan-phet** [comment] 2019-10-31 18:10
<img width="464" alt="Screen Shot 2019-10-31 at 12 09 32 PM" src="https://user-images.githubusercontent.com/40698031/67974089-58ed5500-fbd7-11e9-80c0-bee2abede401.png">

**Comment by pixelzoom** [comment] 2019-10-31 18:34
Good find @megan-phet.  I have reproduced in master and 1.0.0-rc.1. What we're seeing here is the vector label (`|a| = -15`) and the label on it's x component vector (`15.0`).   The y component label is hidden because its magnitude is 0.  

Even if I fix the overlap issues, I'm not sure what value there is to to labeling only one of the component vectors when one of them is zero.  Examples of the 4 cases:

a&#8407; = <10,0>
<img width="266" alt="screenshot_1664" src="https://user-images.githubusercontent.com/3046552/67975605-0c574900-fbda-11e9-8def-e95755464f24.png">

a&#8407; = <-10,0>
<img width="240" alt="screenshot_1665" src="https://user-images.githubusercontent.com/3046552/67975612-0e210c80-fbda-11e9-8411-9d8c7ca06686.png">

a&#8407; = <0,10>
<img width="194" alt="screenshot_1667" src="https://user-images.githubusercontent.com/3046552/67975617-0f523980-fbda-11e9-8c09-ec94827d3b64.png">

a&#8407; = <0,-10>
<img width="198" alt="screenshot_1668" src="https://user-images.githubusercontent.com/3046552/67975620-10836680-fbda-11e9-8e04-f86d87617c53.png">

Proposal: When either x or y is zero, hide _both_ component vector labels.  Do this for the "triangle" and "parallelogram" component styles. The "projection" style would continue to show the non-zero component vector's label. 

@arouinfar your thoughts?

**Comment by arouinfar** [comment] 2019-10-31 19:26
> Proposal: When either x or y is zero, hide both component vector labels. Do this for the "triangle" and "parallelogram" component styles. The "projection" style would continue to show the non-zero component vector's label.

Excellent suggestion, let's do it. In the triangle and parallelogram styles, the non-zero component of a 1D vector is redundant and I think hiding it would certainly look cleaner.

**Comment by pixelzoom** [comment] 2019-10-31 19:28
Thanks @arouinfar, I'll proceed.

**Comment by pixelzoom** [comment] 2019-10-31 20:38
Changed as proposed in master and 1.0.   @arouinfar would you please verify in master?

**Comment by loganbraywork** [comment] 2019-10-31 20:46
Noticed this as well, in the Explore 2D screen if the vector length is <4 and the angle is located within quadrant 1 and 4 the length label for the vector will overlap with the angle. This same behavior does not occur in the Equations Lab. Is it covered in the fix?

**Comment by pixelzoom** [comment] 2019-10-31 20:48
@loganbraywork Thanks for reporting. Not the same issue, and I don't quite follow. Please create a new issue, with steps to reproduce and visuals. Thanks!

**Comment by KatieWoe** [comment] 2019-11-01 15:05
Noting that it can occur in https://github.com/phetsims/QA/issues/446 too

**Comment by pixelzoom** [comment] 2019-11-01 15:23
Thanks @KatieWoe, noted.  That can be said for most (all?) of the issues for  phetsims/QA#445.  The next RC of `_Vector Addition: Equations` will be built using vector-addition 1.0 latest, so will be incorporated.

**Comment by arouinfar** [comment] 2019-11-01 22:02
Looks good in master @pixelzoom

**Comment by KatieWoe** [comment] 2019-11-05 19:15
This fix has been implemented. Some overlap can still occur under similar circumstances with small slopes.  If this is acceptable please close.
![someoverlap](https://user-images.githubusercontent.com/41024075/68238215-f4ab0680-ffc5-11e9-828f-2fb747021344.png)

**Comment by arouinfar** [comment] 2019-11-05 19:19
Thanks @KatieWoe. I'd say this overlap is akin to #267, so closing.

**Closed by arouinfar** 2019-11-05 19:19 UTC
Labels: design:general, status:fixed-awaiting-deploy
