### ISSUE TITLE
Upside-down f vector when d vector and e vector cancel

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/vector-addition#260] opened 2019-10-28 22:40 UTC
**Test Device**

MacBook Air

**Operating System**

macOS 10.14.6

**Browser**

Safari 13.0.2

**Problem Description**

For https://github.com/phetsims/QA/issues/445. If you follow the steps to reproduce, you will see an upside-down f vector, which happens to be the zero vector.

macOS 10.13.6, macOS 10.14.6, and macOS 10.15.1 Beta + their respective versions of Safari have this issue.

**Steps to Reproduce**

I don't think you have to follow these steps in this exact order. Also, I'm not sure it's necessary to have all checkboxes checked.

1. Equations screen.
2. Magenta vector button.
3. **d** - **e** = **f**.
4. All checkboxes checked.
5. Go to the base vectors menu.
6. Increase theta_**d** to 45 degrees.
7. Decrease |**e**| to 5.
8. You should see an upside-down |**f**| = 0.0.

This also works on **d** + **e** = **f** if you have **d** = -**e**.

**Visuals**

![issue](https://user-images.githubusercontent.com/31285590/67723281-235f2680-f9a1-11e9-8895-41f3990d6f30.png)

<details>
<summary><b>Troubleshooting Information</b></summary>
!!!!! DO NOT EDIT !!!!!
Name: ‪Vector Addition‬
URL: https://phet-dev.colorado.edu/html/vector-addition/1.0.0-rc.1/phet/vector-addition_all_phet.html
Version: 1.0.0-rc.1 2019-10-23 17:30:32 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.2 Safari/605.1.15
Language: en-US
Window: 1440x837
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment] 2019-10-28 22:53
Hmmm... I've followed these steps numerous times immediately after loading the sim, and I can't reproduce.  I've tried both master and [1.0.0-rc.1](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-rc.1/phet/vector-addition_all_phet.html).  @lmulhall-phet were these steps reproducible immediately after starting the sim, or did you do some other things before the steps listed?

**Comment by lmulhall-phet** [comment] 2019-10-28 22:54
> were these steps reproducible immediately after starting the sim

Yes.

> My test platform is macOS 10.14.6 + Chrome 77. But I would expect this bug to be independent of platform.

It doesn't happen on Chrome.

**Comment by pixelzoom** [comment] 2019-10-28 23:01
Wow, really odd.  I have reproduced on macOS 10.4.6 + Safari 13.0.1.  It is necessary to have the "Values" checkbox checked, but not the "Angles" checkbox.  Steps 3-7 can be done in any order.

Investigating...

**Comment by pixelzoom** [comment] 2019-10-28 23:10
I verified that it's not a problem on macOS 10.14.6 + Firefox 70.0.

I've also noticed that the position of the 'f' vector label is incorrect, regardless of whether "Value" checkbox is checked.  The 'f' vector's tail is at <25,5>, and that it where the label should be centered for a zero-magitude vector.  Instead, it's a bit above <25,5>, around <25,6.5>, see screenshots below.  This anomaly is also Safari-specific; it's in the correct location on Chrome. 

"Values" checked:

<img width="491" alt="screenshot_1643" src="https://user-images.githubusercontent.com/3046552/67724649-52779700-f9a5-11e9-9473-1605e9711ad5.png">

"Values" unchecked:

<img width="463" alt="screenshot_1642" src="https://user-images.githubusercontent.com/3046552/67724653-57d4e180-f9a5-11e9-860c-63aa4e384816.png">

**Comment by pixelzoom** [comment] 2019-10-28 23:13
I can't reproduce on the "Cartesian" (blue vectors) scene.   The orientation and position of the 'c' label is correct with all of my macOS 10.14.6 browsers, including Safari.

**Comment by pixelzoom** [comment] 2019-10-28 23:48
Changing d and e to magnitude '6' on Safari, the orientation is correct, see below.  And going back to magnitude '5', the problem is still present.

<img width="940" alt="screenshot_1645" src="https://user-images.githubusercontent.com/3046552/67725051-a0d96580-f9a6-11e9-9a74-384943044225.png">

**Comment by pixelzoom** [comment] 2019-10-29 01:00
Vector label positioning and rotation are handled in `RootVectorNode.updateLabelPositioning`.

**Comment by pixelzoom** [comment] 2019-10-29 01:46
Fixed in master and 1.0 in the above commit.  The problem was actually the vector magnitude.  On Chrome and Firefox, it was precisely zero.  On Safari, it was a very small non-zero value.  So the solution was to treat any value smaller than 1E10 as effectively zero.  

@lmulhall-phet please verify in master.  The label's rotation _and position_ should be correct.  Specifically, its rotation should be zero, and it should be centered at (25,5).  If it looks OK, unassign and change the label to "fixed-awaiting-deploy".

**Comment by arouinfar** [comment] 2019-10-29 03:04
Looks like this was a tricky one. Nice find @lmulhall-phet!

**Comment by pixelzoom** [comment] 2019-10-29 04:10
One more cleanup step... I factored out `const ZERO_MAGNITUDE_THRESHOLD = 1E-10;` in the above commits to master and 1.0.

**Comment by lmulhall-phet** [comment] 2019-10-30 21:43
Looks fixed to me, @pixelzoom.

Just for my edification, could you explain to me why this bug occurred? From what I understand, all numbers in JavaScript are double-precision IEEE 754 values. From what you said, it sounds like |**d**| - |**e**| was being compared to 0 and |**d**| - |**e**| = 0 + epsilon. I'm wondering how this could be the case if both |**d**| and |**e**| have the exact same encoding.

**Comment by pixelzoom** [comment] 2019-10-30 22:09
Sorry @lmulhall-phet, I have no idea why Chrome and Firefox result in a vector magnitude that is exactly zero, while Safari results in 8.881784197001252e-16.  Could be indicative of a more subtle sum bug, or DOT/Vector2 bug, or difference in Safari.  If I can find time, I might come back to this. But unfortunately I don't have time to investigate further right now.

**Comment by pixelzoom** [comment] 2019-10-30 22:12
As a quick experiment in the browser console:

```
> var d = phet.dot.Vector2.createPolar( 5, Math.PI / 4 )
> var e = phet.dot.Vector2.createPolar( 5, Math.PI / 4 )
> d.plus( e ).magnitude
10
> d.minus( e ).magnitude
0
```

This yields the same results on Chrome, Firefox, and Safari.  So this would point to this being a sim-specific problem.

**Comment by lmulhall-phet** [comment] 2019-10-30 22:25
Thanks, @pixelzoom. I was just curious because this is what we're learning in Computer Systems.

**Comment by pixelzoom** [comment] 2019-10-30 22:29
Investigating further, because I'm curious....  I added these lines of code to `EquationVectorSet`, to print the vector values to the console:

```js
vector.vectorComponentsProperty.link( vectorComponents => {
  console.log( `${symbol} x=${vectorComponents.x} y=${vectorComponents.y} magnitude=${vectorComponents.magnitude} angle=${vectorComponents.angle}`)
} );

 this.sumVector.vectorComponentsProperty.link( vectorComponents => {
  console.log( `${this.sumVector.symbol} x=${vectorComponents.x} y=${vectorComponents.y} magnitude=${vectorComponents.magnitude} angle=${vectorComponents.angle}`)
} );
```

Here's the output for state shown in https://github.com/phetsims/vector-addition/issues/260#issuecomment-547219184:

```
// Chrome and Firefox
d x=3.5355339059327378 y=3.5355339059327373 magnitude=5 angle=0.7853981633974483
e x=3.5355339059327378 y=3.5355339059327373 magnitude=5 angle=0.7853981633974483
f x=0 y=0 magnitude=0 angle=0
```

// Safari
e x=3.5355339059327386 y=3.5355339059327373 magnitude=5.000000000000001 angle=0.7853981633974481
d x=3.5355339059327378 y=3.5355339059327373 magnitude=5 angle=0.7853981633974483
f x=-8.881784197001252e-16 y=0 magnitude=8.881784197001252e-16 angle=3.141592653589793
```

The discrepancy here is that `|e|` is `5.000000000000001` on Safari.  I have no immediate guess as to why.

**Comment by pixelzoom** [comment] 2019-11-05 23:45
Passed QA in for phetsims/QA#445 and phetsims/QA#446.  Closing.

**Closed by pixelzoom** 2019-11-05 23:45 UTC
Labels: status:ready-for-qa, type:bug
