### ISSUE TITLE
Sum vectors visibility bug on Lab screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#160] opened 2019-09-03 00:48 UTC
Steps to reproduce:

1. Lab screen
2. check both Sum checkboxes.
3. select one sum on graph
4. other sum disappears from graph

E.g.:

<img width="915" alt="screenshot_1429" src="https://user-images.githubusercontent.com/3046552/64136928-f9372100-cdc2-11e9-9091-56a73542f366.png">

**Comment by pixelzoom** [comment] 2019-09-18 16:42
Apparently its just the label that's disappearing when the sum is zero.   On the _Lab_ screen, only one sum vector is labeled.  It's labeled if it's selected, or if one of its associated vectors is selected. 

For example:

1. Lab screen
2. drag one blue vector to the graph
3. drag one red vector to the graph
4. check both Sum checkboxes.
5. select one sum on graph, the other sum's label disappears

<img width="1013" alt="screenshot_1493" src="https://user-images.githubusercontent.com/3046552/65167283-7c7d8700-d9ff-11e9-8c4b-7b2b75263190.png">

Options:

(1) Always show both sum vectors as s&#8407;. This is currently the case when following the steps in https://github.com/phetsims/vector-addition/issues/160#issue-488346460.  It could be confusing to have the same label on 2 vectors.

(2) Always show both sum labels, but use subscripts, i.e. s&#8407;<sub>1</sub> and s&#8407;<sub>2</sub>, include those labels in the Sum checkboxes, e.g. "Sum s&#8407;<sub>1</sub>". We might want to also change "Sum" checkboxes first 2 screens to "Sum s&#8407;".

(3) Don't show a label for any zero-magnitude sum vector. This would be inconsistent with other screens, so harder to implement.

(4) Do nothing, live with this weirdness.

My preference is option (3).  @arouinfar, your call.

**Comment by pixelzoom** [comment] 2019-09-23 19:27
Raising priority, since we're trying to get into dev testing by 10/1.

**Comment by pixelzoom** [comment] 2019-09-23 19:44
See https://github.com/phetsims/vector-addition/issues/187#issuecomment-534254051.

**Comment by pixelzoom** [comment] 2019-09-23 22:44
Addressed  in the above commit.  The sum vector will only be displayed when the Sum checkbox is checked _and_ the sum is defined. 

@arouinfar please review in master.

**Comment by pixelzoom** [comment] 2019-09-24 17:38
Rats, this is not totally fixed -- the value is being shown when "Values" is checked.

<img width="532" alt="screenshot_1502" src="https://user-images.githubusercontent.com/3046552/65535963-b3e8a980-debf-11e9-9f19-7f6899b07639.png">

**Comment by pixelzoom** [comment] 2019-09-24 18:10
Fixed again :)  I had to introduce a new BooleanProperty in SumVector, `isDefinedProperty`.

@arouinfar please review in master.

**Comment by pixelzoom** [comment] 2019-09-24 18:43
Fix also appears in https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.20/phet/vector-addition_en_phet.html

**Comment by arouinfar** [comment] 2019-09-25 17:17
Looks like the changes proposed in https://github.com/phetsims/vector-addition/issues/187#issuecomment-534254051 plus `isDefinedProperty` have done the trick. I am unable to reproduce this bug. Closing.

**Closed by arouinfar** 2019-09-25 17:17 UTC
Labels: design:general, status:ready-for-review, type:bug
