### ISSUE TITLE
When should 180 be positive or negative

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/vector-addition#251] opened 2019-10-25 22:36 UTC
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/445
When a vector's angle is 180 (or -180) it can be difficult to determine which it should be.  It seems to be determined partly by cursor position and partly by the direction it came. This is mostly seen in the pink, angle controlled vectors.  The sum vector and how it determines which it has also can appear odd.

**Visuals**
![ezgif com-optimize](https://user-images.githubusercontent.com/41024075/67608439-7341b180-f745-11e9-93cb-75c79c05c415.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Vector Addition‬
URL: https://phet-dev.colorado.edu/html/vector-addition/1.0.0-rc.1/phet/vector-addition_all_phet.html
Version: 1.0.0-rc.1 2019-10-23 17:30:32 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment] 2019-10-26 00:24
It took me awhile to reproduce this, so a few notes:

* This is most easily reproduced on the Polar scene.
* If you are rotating the vector counterclockwise, the value is 180.
* If you are rotating the vector clockwise, the value is -180.
* When the value is 180 or -180, you can make its sign change by moving the pointer slightly above (+180) or below (-180) the vector.
* The sign of the value is determined by common code (`DOT/Vector2 getAngle`), and Javascript's built-in `Math.atan2`.

That said, I'm not sure if this is really a problem or worth addressing.

**Comment by pixelzoom** [comment] 2019-10-26 00:41
Investigating further...  Javascript's builtin `Math.atan2( y, x )` function is determining the sign.  If y is positive, then the angle is positive.  If y is negative, then the angle is negative.  For example:

```
> Math.atan2( 1, 1 )
0.7853981633974483
> Math.atan2( -1, 1 )
-0.7853981633974483
```

So when you're rotating a vector, the sign is determined by whether the pointer is above or below the horizontal.   And that corresponds to the current behavior of the sim.   Since `Math.atan2` is internal to `DOT/Vector2.getAngle`, I can't change that behavior.   I'd need to take the value and do something special when it's +-180.

**Comment by arouinfar** [comment] 2019-10-26 03:26
The behavior generally makes sense, but what looks a bit odd to me is this case in Cartesian mode. Even when dragging through negative angles to reach 180*, the final angle is always positive. It is impossible to create an angle of -180* by rotating a Cartesian vector, which seems a bit odd to me.
![180](https://user-images.githubusercontent.com/8419308/67613664-4903ea00-f76d-11e9-8943-9132e4a88023.gif)

If this is a natural byproduct of the way Dot/Math, that's fine by me.  I don't want to mess with any custom solutions. Back to @pixelzoom to confirm this example is exhibiting the expected behavior.

**Comment by pixelzoom** [comment] 2019-10-26 03:31
@arouinfar Things are a little different in Cartesian mode. x and y components are snapping to integers. So in the case above, y snaps to 0, x snaps to -8,. That results in `Math.atan2( 0, -8 )` which is `3.141592653589793` radians, which is 180 degrees.  So yes, it's impossible to get -180.

If that makes sense, feel free to close as "won't fix".

**Comment by pixelzoom** [comment] 2019-10-26 03:34
Btw... If we did something like "always show -180 as +180", we have a problem with the theta pickers for base vectors, which range from [-180,180].   We could make those pickers range from [-179, 180] (and wrap around?) but I don't think was want to do there.

**Comment by arouinfar** [comment] 2019-10-26 03:34
Thanks for the clarification @pixelzoom. I'm content to close this as `type:wontfix`.

**Closed** 2019-10-26 03:34 UTC
Labels: type:bug, type:wontfix
